# Generated by Django 5.2.1 on 2025-06-25 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[(1, 'Наложеный платёж'), (2, 'Безналичный')])),
                ('delivery_type', models.CharField(choices=[(1, 'Самовывоз'), (2, 'Новая почта')])),
                ('delivery_price', models.PositiveIntegerField()),
                ('payment', models.PositiveIntegerField()),
                ('products', models.ManyToManyField(to='cart.cartmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
