# Generated by Django 5.2.1 on 2025-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_ordersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='delivery_type',
            field=models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Новая почта')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Наложеный платёж'), ('2', 'Безналичный')]),
        ),
    ]
