# Generated by Django 5.2.1 on 2025-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tagsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='products/')),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colors', models.ManyToManyField(to='products.colorsmodel')),
                ('sizes', models.ManyToManyField(to='products.sizesmodel')),
                ('tags', models.ManyToManyField(to='products.tagsmodel')),
            ],
        ),
    ]
